name: CI

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  push:
    branches:
      - dev
    tags:
      - "v*-beta.*"
      - "v*-rc.*"
  pull_request:
    branches:
      - dev

env:
  MORYX_OPTIMIZE_CODE: "false"
  MORYX_BUILD_CONFIG: "Release"
  MORYX_BUILDNUMBER: ${{github.run_number}}
  MORYX_NUGET_APIKEY: ${{secrets.MYGET_TOKEN}}
  MORYX_PACKAGE_TARGET: "https://www.myget.org/F/moryx/api/v2/package"

jobs:
  Build:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Build HTML
        shell: pwsh
        run: .\Build.ps1 -BuildHtml

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
    
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2

      - name: Build
        shell: pwsh
        run: ./Build.ps1 -Build -Pack

      - name: Upload package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: artifacts/Packages/
          retention-days: 1

  Documentation:
    needs: [Build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate docFx
        shell: pwsh
        run: ./Build.ps1 -GenerateDocs

      - name: Upload documentation results
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: artifacts/Documentation/
          retention-days: 1

  Publish:
    needs: [Build]
    if: (github.event_name == 'push')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2
  
      - name: Download package artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: artifacts/Packages/

      - name: Publish packages
        shell: pwsh
        run: ./Build.ps1 -Publish