name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  MORYX_OPTIMIZE_CODE: "false"
  MORYX_BUILD_CONFIG: "Release"
  MORYX_BUILDNUMBER: ${{github.run_number}}
  MORYX_BRANCH: "dev" #TODO: ${{github.ref}} parse branch name
  MORYX_CODECOV_SECRET: ${{secrets.CODECOV_TOKEN}}
  MORYX_NUGET_APIKEY: ${{secrets.MYGET_TOKEN}}

jobs:
  Build:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Build HTML
        shell: pwsh
        run: .\Build.ps1 -BuildHtml

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
    
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2

      - name: Build
        shell: pwsh
        run: ./Build.ps1 -Build
  Publish:
    needs: [Build]
    if: (github.event_name == 'push')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Set assembly versions
        shell: pwsh
        run: ./Build.ps1 -SetAssemblyVersion

      - name: Build HTML
        shell: pwsh
        run: .\Build.ps1 -BuildHtml
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2
  
      - name: Build
        shell: pwsh
        run: ./Build.ps1 -Build

      - name: Pack & Publish
        shell: pwsh
        run: ./Build.ps1 -Pack -Publish